version: "3.3"

services:
  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
    command: /cloud_sql_proxy -instances=tidy-tine-473718-a0:asia-southeast1:hrm-db=tcp:0.0.0.0:3306
    ports:
      - "3306:3306"

  node-app:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - cloud-sql-proxy

